[alembic]
script_location = alembic
prepend_sys_path = .

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARNING
handlers = console
qualname =

[logger_sqlalchemy]
level = WARNING
handlers = console
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers = console
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stdout,)
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s

[alembic:main]
script_location = alembic
prepend_sys_path = .
sqlalchemy.url = postgresql+asyncpg://sms_user:sms_password@localhost:5432/school_management

[alembic:test]
sqlalchemy.url = postgresql+asyncpg://sms_user:sms_password@localhost:5432/school_management_test