"""Add teacher_subjects m2m

Revision ID: 0792aee98f56
Revises: f1f6528631a4
Create Date: 2026-08-14 08:06:28.004927

"""
from typing import Set, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0792aee98f56'
down_revision = 'f1f6528631a4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
    DO $$
    BEGIN
        IF NOT EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'teacher_subjects') THEN
            CREATE TABLE teacher_subjects (
                teacher_id INTEGER NOT NULL,
                subject_id INTEGER NOT NULL,
                PRIMARY KEY (teacher_id, subject_id),
                FOREIGN KEY(subject_id) REFERENCES subjects (id) ON DELETE CASCADE,
                FOREIGN KEY(teacher_id) REFERENCES teachers (id) ON DELETE CASCADE
            );
        END IF;
    END
    $$;
    """)
    
    # Preserve existing data
    op.execute("""
        INSERT INTO teacher_subjects (teacher_id, subject_id)
        SELECT teacher_id, id FROM subjects
        WHERE teacher_id IS NOT NULL;
    """)

    op.drop_constraint('fk_subjects_teacher_id', 'subjects', type_='foreignkey')
    op.drop_column('subjects', 'teacher_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_subjects_teacher_id', 'subjects', 'teachers', ['teacher_id'], ['id'], ondelete='SET NULL')
    
    # Try to restore some data (will only restore one teacher per subject)
    op.execute("""
        UPDATE subjects
        SET teacher_id = ts.teacher_id
        FROM (SELECT subject_id, MIN(teacher_id) as teacher_id FROM teacher_subjects GROUP BY subject_id) ts
        WHERE subjects.id = ts.subject_id;
    """)
    
    op.drop_table('teacher_subjects')
    # ### end Alembic commands ###