"""Add UniqueConstraint to Grade

Revision ID: 084b5bfbd2de
Revises: beccd7392fdd
Create Date: 2026-08-11 05:09:11.844515

"""
from typing import Set, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '084b5bfbd2de'
down_revision = 'beccd7392fdd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_student_subject_exam', 'grades', ['student_id', 'subject_id', 'exam_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_student_subject_exam', 'grades', type_='unique')
    # ### end Alembic commands ###