"""add_missing_timestamps

Revision ID: 1a3dd83cf341
Revises: a4e5bc8d942f
Create Date: 2026-08-11 10:09:15.319074

"""
from typing import Set, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a3dd83cf341'
down_revision = 'a4e5bc8d942f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedules', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('schedules', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('subjects', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('subjects', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subjects', 'updated_at')
    op.drop_column('subjects', 'created_at')
    op.drop_column('schedules', 'updated_at')
    op.drop_column('schedules', 'created_at')
    # ### end Alembic commands ###