"""Add teacher_id to exam_subject_slots

Revision ID: 4508bde8e2c8
Revises: 0792aee98f56
Create Date: 2026-08-14 10:26:47.881723

"""
from typing import Set, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4508bde8e2c8'
down_revision = '0792aee98f56'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_subject_slots', sa.Column('teacher_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'exam_subject_slots', 'teachers', ['teacher_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exam_subject_slots', type_='foreignkey')
    op.drop_column('exam_subject_slots', 'teacher_id')
    # ### end Alembic commands ###