"""add exam total_marks

Revision ID: 582cbe85b3db
Revises: e7732819b7dc
Create Date: 2026-08-13 05:20:47.629524

"""
from typing import Set, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '582cbe85b3db'
down_revision = 'e7732819b7dc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exams', sa.Column('total_marks', sa.Float(), nullable=True))
    
    # Backfill existing exams
    conn = op.get_bind()
    setting = conn.execute(sa.text("SELECT value FROM system_settings WHERE key = 'default_exam_marks_scale'")).scalar()
    try:
        default_scale = float(setting) if setting else 100.0
    except (ValueError, TypeError):
        default_scale = 100.0
    
    op.execute(sa.text(f"UPDATE exams SET total_marks = {default_scale} WHERE total_marks IS NULL"))
    op.alter_column('system_settings', 'type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'string'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('system_settings', 'type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'string'::character varying"))
    op.drop_column('exams', 'total_marks')
    # ### end Alembic commands ###