"""Add teacher_id to leave_requests

Revision ID: 794ab185550f
Revises: a978531c417d
Create Date: 2026-08-11 06:38:12.461277

"""
from typing import Set, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '794ab185550f'
down_revision = 'a978531c417d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leave_requests', sa.Column('teacher_id', sa.Integer(), nullable=True))
    op.alter_column('leave_requests', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'leave_requests', 'teachers', ['teacher_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'leave_requests', type_='foreignkey')
    op.alter_column('leave_requests', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('leave_requests', 'teacher_id')
    # ### end Alembic commands ###