"""Exam System Redesign

Revision ID: 8c50e737dac6
Revises: e2b5a010e43f
Create Date: 2026-08-11 07:14:06.964780

"""
from typing import Set, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8c50e737dac6'
down_revision = 'e2b5a010e43f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_subject_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_subject_slots_id'), 'exam_subject_slots', ['id'], unique=False)
    
    op.add_column('exam_submissions', sa.Column('exam_subject_slot_id', sa.Integer(), nullable=False))
    op.drop_constraint('uq_exam_submission', 'exam_submissions', type_='unique')
    op.create_unique_constraint('uq_exam_submission', 'exam_submissions', ['exam_subject_slot_id', 'student_id'])
    op.drop_constraint('exam_submissions_exam_id_fkey', 'exam_submissions', type_='foreignkey')
    op.create_foreign_key(None, 'exam_submissions', 'exam_subject_slots', ['exam_subject_slot_id'], ['id'], ondelete='CASCADE')
    op.drop_column('exam_submissions', 'exam_id')
    op.drop_constraint('exams_subject_id_fkey', 'exams', type_='foreignkey')
    op.drop_constraint('exams_class_id_fkey', 'exams', type_='foreignkey')
    op.drop_column('exams', 'start_date')
    op.drop_column('exams', 'subject_id')
    op.drop_column('exams', 'class_id')
    op.drop_column('exams', 'end_date')
    op.add_column('grades', sa.Column('letter_grade', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grades', 'letter_grade')
    op.add_column('exams', sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('exams', sa.Column('class_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('exams', sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('exams', sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_foreign_key('exams_class_id_fkey', 'exams', 'classes', ['class_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('exams_subject_id_fkey', 'exams', 'subjects', ['subject_id'], ['id'], ondelete='CASCADE')
    op.add_column('exam_submissions', sa.Column('exam_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'exam_submissions', type_='foreignkey')
    op.create_foreign_key('exam_submissions_exam_id_fkey', 'exam_submissions', 'exams', ['exam_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_exam_submission', 'exam_submissions', type_='unique')
    op.create_unique_constraint('uq_exam_submission', 'exam_submissions', ['exam_id', 'student_id'])
    op.drop_column('exam_submissions', 'exam_subject_slot_id')
    op.drop_index(op.f('ix_exam_subject_slots_id'), table_name='exam_subject_slots')
    op.drop_table('exam_subject_slots')
    # ### end Alembic commands ###