"""Add class_id to exams

Revision ID: 907a41d2e3bf
Revises: 4508bde8e2c8
Create Date: 2026-08-14 10:38:44.348039

"""
from typing import Set, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '907a41d2e3bf'
down_revision = '4508bde8e2c8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exams', sa.Column('class_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'exams', 'classes', ['class_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exams', type_='foreignkey')
    op.drop_column('exams', 'class_id')
    # ### end Alembic commands ###