"""Add status enums

Revision ID: a4e5bc8d942f
Revises: 8c50e737dac6
Create Date: 2026-08-11 09:57:42.604271

"""
from typing import Set, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a4e5bc8d942f'
down_revision = '8c50e737dac6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enums manually because autogenerate missed them
    assignment_status_enum = sa.Enum('DRAFT', 'PUBLISHED', 'CLOSED', name='assignmentstatus')
    assignment_status_enum.create(op.get_bind())
    
    exam_status_enum = sa.Enum('DRAFT', 'SCHEDULED', 'COMPLETED', 'CANCELLED', name='examstatus')
    exam_status_enum.create(op.get_bind())
    
    leave_request_status_enum = sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', name='leaverequeststatus')
    leave_request_status_enum.create(op.get_bind())

    op.add_column('assignments', sa.Column('status', assignment_status_enum, nullable=False, server_default='DRAFT'))
    op.alter_column('exam_subject_slots', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.add_column('exams', sa.Column('status', exam_status_enum, nullable=False, server_default='DRAFT'))
    
    # Drop old column and add new one for leave_requests
    op.drop_column('leave_requests', 'status')
    op.add_column('leave_requests', sa.Column('status', leave_request_status_enum, nullable=False, server_default='PENDING'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('leave_requests', 'status',
               existing_type=sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', name='leaverequeststatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('exams', 'status')
    op.alter_column('exam_subject_slots', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('assignments', 'status')
    # ### end Alembic commands ###