"""Add class_id and subject_id to Exam

Revision ID: a978531c417d
Revises: 084b5bfbd2de
Create Date: 2026-08-11 05:13:55.852987

"""
from typing import Set, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a978531c417d'
down_revision = '084b5bfbd2de'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exams', sa.Column('class_id', sa.Integer(), nullable=True))
    op.add_column('exams', sa.Column('subject_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'exams', 'subjects', ['subject_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'exams', 'classes', ['class_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exams', type_='foreignkey')
    op.drop_constraint(None, 'exams', type_='foreignkey')
    op.drop_column('exams', 'subject_id')
    op.drop_column('exams', 'class_id')
    # ### end Alembic commands ###