"""Update fee structure

Revision ID: beccd7392fdd
Revises: e6632819b7db
Create Date: 2026-08-11 01:51:39.075632

"""
from typing import Set, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'beccd7392fdd'
down_revision = 'e6632819b7db'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classes', sa.Column('fee_amount', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('fees', sa.Column('waiver_percentage', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('fees', sa.Column('amount_paid', sa.Float(), nullable=False, server_default='0.0'))
    op.drop_column('fees', 'amount')
    op.drop_index('ix_subjects_teacher_id', table_name='subjects')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_subjects_teacher_id', 'subjects', ['teacher_id'], unique=False)
    op.add_column('fees', sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('fees', 'amount_paid')
    op.drop_column('fees', 'waiver_percentage')
    op.drop_column('classes', 'fee_amount')
    # ### end Alembic commands ###