"""Add SystemSetting

Revision ID: e2b5a010e43f
Revises: 794ab185550f
Create Date: 2026-08-11 07:12:16.282300

"""
from typing import Set, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2b5a010e43f'
down_revision = '794ab185550f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###