"""add_exam_submission_attachment

Revision ID: e6632819b7db
Revises: 003
Create Date: 2026-08-10 11:56:45.227106

"""
from typing import Set, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6632819b7db'
down_revision = '003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_submissions', sa.Column('attachment_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam_submissions', 'attachment_url')
    # ### end Alembic commands ###