"""add assignment total_marks

Revision ID: e7732819b7dc
Revises: e6632819b7db
Create Date: 2026-08-13 10:25:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'e7732819b7dc'
down_revision = '1a3dd83cf342'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('total_marks', sa.Integer(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignments', 'total_marks')
    # ### end Alembic commands ###
