"""add assignment_id to grades

Revision ID: f0b1caff7a64
Revises: 907a41d2e3bf
Create Date: 2026-08-14 11:22:14.113561

"""
from typing import Set, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0b1caff7a64'
down_revision = '907a41d2e3bf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grades', sa.Column('assignment_id', sa.Integer(), nullable=True))
    op.drop_constraint('uq_student_subject_exam', 'grades', type_='unique')
    op.create_unique_constraint('uq_student_subject_assessment', 'grades', ['student_id', 'subject_id', 'exam_id', 'assignment_id'])
    op.create_foreign_key(None, 'grades', 'assignments', ['assignment_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'grades', type_='foreignkey')
    op.drop_constraint('uq_student_subject_assessment', 'grades', type_='unique')
    op.create_unique_constraint('uq_student_subject_exam', 'grades', ['student_id', 'subject_id', 'exam_id'])
    op.drop_column('grades', 'assignment_id')
    # ### end Alembic commands ###