"""Add unique constraint for fees

Revision ID: f0f6528631a3
Revises: bfe7e8a55a73
Create Date: 2026-08-13 05:59:15.751497

"""
from typing import Set, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0f6528631a3'
down_revision = 'bfe7e8a55a73'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_student_academic_year', 'fees', ['student_id', 'academic_year'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_student_academic_year', 'fees', type_='unique')
    # ### end Alembic commands ###